### ISSUE TITLE
Color logs is not working on Xcode 7

### ISSUE THREAD

**Issue by patgdut** [codeFi/XcodeLogger#1]
I try DLog_ERROR(@"Test");
Here is the output copy from my console:
[[fg255,0,0;DEBUG:ERROR[;](11:41:19)=> [>0x125f685c0<]:LLShell.m:[#52]:[> -[LLShell application:didFinishLaunchingWithOptions:] <]
[fg255,255,255;[bg255,0,0;Test[;

Am I missing something?

**Comment by codeFi** [comment]
Have you updated the Xcode Colors plugin? 
I've updated my fork a few days ago. Clone, build it again and restart Xcode.

**Comment by patgdut** [comment]
Thanks, it's working now!
